version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    networks:
      - internal-net

  nginx:
    image: nginx:latest
    container_name: backend-nginx
    ports:
      - "8282:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - internal-net

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal-net

volumes:
  pgdata:

networks:
  internal-net:
    driver: bridge
