{{ if .Values.gateway.createSslCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fe-mcsp-certificate
  namespace: istio-system
spec:
  commonName: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
  {{- range $item := .Values.hosts | split "," }}
    - {{ trim $item }}
  {{- end }}
    - localhost
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.gateway.vaultIssuer }}
  privateKey:
    rotationPolicy: Always
  secretName: {{ .Values.gateway.credentialName }}
  subject:
    organizationalUnits:
      - ASSISTENERGY
  usages:
    - server auth
    - client auth
{{/* if .Values.gateway.createSslCertificate */}}{{ end }}
