export enum AppMenuListEnum {
  OVERVIEW = "Overview",
  ASSETS = "ASSETS",
  REMEDIATION = "REMEDIATION",
  INCIDENT = "INCIDENT",
  INCIDENTS = "INCIDENTS",
  HISTORY = "HISTORY",
  ADMINISTRATION = "ADMINISTRATION",
}
