import { inject, Injectable } from "@angular/core";
import { ApiService } from "../../../core/services/api.service";
import { map, Observable, of } from "rxjs";
import {
  IncidentDetail,
  IncidentDetailResponse,
} from "../models/incident-detail.models";
import { environment } from "../../../../environments/environment";
import { API_ENDPOINTS } from "../../../../environments/api-endpoints";

@Injectable({
  providedIn: "root",
})
export class IncidentDetailService {
  private apiService = inject(ApiService);

  private mockedIncidentDetail: IncidentDetail[] = [
    {
      id: 123456789,
      title: "title_185",
      description: "create description_185",
      severity: "high",
      critically: "critical",
      summary: "summary_185",
      tags: "tags_185",
      status: "New",
      createdAt: "2025-05-08T00:00:00.000+00:00",
      events: [
        {
          id: 11,
          name: "event_name_185",
          description: "event description 185",
          type: "type",
          eventDate: "2025-05-14T07:18:24.845+00:00",
          alertLog: "alertLog_185",
          status: "New",
          remediation: {
            id: 6,
            remediationCatalogId: 1,
            description: "remediation description 185",
            status: "New",
            actions: [
              {
                id: 6,
                description: "action description 185",
                note: "update note 185",
                status: "Completed",
                actionType: "Automated",
                asset: {
                  id: 6,
                  shipId: 2,
                  externalAssetId: 1,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "4",
                  frame: "45",
                  type: "FW",
                  mvz: "2",
                  position: "PS",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "Navigation",
                      id: 9,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:14.146+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 10,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:14.157+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:13.610+00:00",
                },
                creationDate: "2025-05-15T08:10:13.606+00:00",
              },
              {
                id: 7,
                description: "action description 142",
                note: "update note 142",
                status: "New",
                actionType: "Automated",
                asset: {
                  id: 7,
                  shipId: 2,
                  externalAssetId: 1,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "3",
                  frame: "103",
                  type: "FW",
                  mvz: "3",
                  position: "SB",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "Navigation",
                      id: 11,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:14.239+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 12,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:14.251+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:14.179+00:00",
                },
                creationDate: "2025-05-15T08:10:14.166+00:00",
              },
              {
                id: 89,
                description: "action description 89",
                note: "update note 89",
                status: "New",
                actionType: "Human",
                asset: {
                  id: 7,
                  shipId: 2,
                  externalAssetId: 1,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "3",
                  frame: "103",
                  type: "FW",
                  mvz: "3",
                  position: "SB",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "Navigation",
                      id: 11,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:14.239+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 12,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:14.251+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:14.179+00:00",
                },
                creationDate: "2025-05-15T08:10:14.166+00:00",
              },
            ],
            creationDate: "2025-05-15T08:10:13.597+00:00",
          },
          creationDate: "2025-05-15T08:10:09.944+00:00",
        },
        {
          id: 12,
          name: "event_name_142",
          description: "event description 142",
          type: "type",
          eventDate: "2025-04-14T07:18:24.845+00:00",
          alertLog: "alertLog_142",
          status: "Rejected",
          remediation: {
            id: 7,
            remediationCatalogId: 1,
            description: "remediation description 142",
            status: "Ignored",
            actions: [
              {
                id: 8,
                description: "action description 141",
                note: "update note 141",
                status: "Ignored",
                actionType: "Automated",
                asset: {
                  id: 8,
                  shipId: 1,
                  externalAssetId: 2,
                  pieceMark: "A2",
                  description: "create description",
                  assetRole: "source",
                  deck: "4",
                  frame: "170",
                  type: "SERVER",
                  mvz: "4",
                  position: "CL",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "functionName3",
                      id: 13,
                      pieceMark: "A2",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:17.505+00:00",
                    },
                    {
                      function: "functionName4",
                      id: 14,
                      pieceMark: "A2",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:17.511+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:17.448+00:00",
                },
                creationDate: "2025-05-15T08:10:17.443+00:00",
              },
              {
                id: 9,
                description: "action description 33",
                note: "update note 33",
                status: "Ignored",
                actionType: "Human",
                asset: {
                  id: 9,
                  shipId: 1,
                  externalAssetId: 2,
                  pieceMark: "A2",
                  description: "create description",
                  assetRole: "source",
                  deck: "1",
                  frame: "120",
                  type: "SERVER",
                  mvz: "3",
                  position: "SB",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "functionName3",
                      id: 15,
                      pieceMark: "A2",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:17.585+00:00",
                    },
                    {
                      function: "functionName4",
                      id: 16,
                      pieceMark: "A2",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:17.597+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:17.525+00:00",
                },
                creationDate: "2025-05-15T08:10:17.518+00:00",
              },
              {
                id: 20,
                description: "action description 20",
                note: "update note 20",
                status: "Ignored",
                actionType: "Automated",
                asset: {
                  id: 8,
                  shipId: 1,
                  externalAssetId: 2,
                  pieceMark: "A2",
                  description: "create description",
                  assetRole: "source",
                  deck: "4",
                  frame: "170",
                  type: "SERVER",
                  mvz: "4",
                  position: "CL",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "functionName3",
                      id: 13,
                      pieceMark: "A2",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:17.505+00:00",
                    },
                    {
                      function: "functionName4",
                      id: 14,
                      pieceMark: "A2",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:17.511+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:17.448+00:00",
                },
                creationDate: "2025-05-15T08:10:17.443+00:00",
              },
              {
                id: 21,
                description: "action description 21",
                note: "update note 21",
                status: "Ignored",
                actionType: "Automated",
                asset: {
                  id: 8,
                  shipId: 1,
                  externalAssetId: 2,
                  pieceMark: "A2",
                  description: "create description",
                  assetRole: "source",
                  deck: "4",
                  frame: "170",
                  type: "SERVER",
                  mvz: "4",
                  position: "CL",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "functionName3",
                      id: 13,
                      pieceMark: "A2",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:17.505+00:00",
                    },
                    {
                      function: "functionName4",
                      id: 14,
                      pieceMark: "A2",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:17.511+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:17.448+00:00",
                },
                creationDate: "2025-05-15T08:10:17.443+00:00",
              },
              {
                id: 22,
                description: "action description 22",
                note: "update note 22",
                status: "Ignored",
                actionType: "Automated",
                asset: {
                  id: 8,
                  shipId: 1,
                  externalAssetId: 2,
                  pieceMark: "A2",
                  description: "create description",
                  assetRole: "source",
                  deck: "4",
                  frame: "170",
                  type: "SERVER",
                  mvz: "4",
                  position: "CL",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "functionName3",
                      id: 13,
                      pieceMark: "A2",
                      percentage: "100",
                      creationDate: "2025-05-15T08:10:17.505+00:00",
                    },
                    {
                      function: "functionName4",
                      id: 14,
                      pieceMark: "A2",
                      percentage: "50",
                      creationDate: "2025-05-15T08:10:17.511+00:00",
                    },
                  ],
                  creationDate: "2025-05-15T08:10:17.448+00:00",
                },
                creationDate: "2025-05-15T08:10:17.443+00:00",
              },
            ],
            creationDate: "2025-05-15T08:10:17.437+00:00",
          },
          creationDate: "2025-05-15T08:10:14.255+00:00",
        },
        {
          id: 13,
          name: "event_name_186",
          description: "event description 186",
          type: "type",
          eventDate: "2025-05-16T07:18:24.845+00:00",
          alertLog: "alertLog_186",
          status: "New",
          remediation: {
            id: 8,
            remediationCatalogId: 1,
            description: "remediation description 186",
            status: "Completed",
            actions: [
              {
                id: 10,
                description: "action description 186",
                note: "update note 186",
                status: "Completed",
                actionType: "Human",
                asset: {
                  id: 10,
                  shipId: 2,
                  externalAssetId: 3,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "2",
                  frame: "202",
                  type: "SW",
                  mvz: "5",
                  position: "PS",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "HVAC",
                      id: 17,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-16T08:10:14.146+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 18,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-16T08:10:14.157+00:00",
                    },
                  ],
                  creationDate: "2025-05-16T08:10:13.610+00:00",
                },
                creationDate: "2025-05-16T08:10:13.606+00:00",
              },
              {
                id: 50,
                description: "action description 50",
                note: "update note 50",
                status: "In Progress",
                actionType: "Assisted",
                asset: {
                  id: 10,
                  shipId: 2,
                  externalAssetId: 3,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "2",
                  frame: "202",
                  type: "SW",
                  mvz: "5",
                  position: "PS",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "HVAC",
                      id: 17,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-16T08:10:14.146+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 18,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-16T08:10:14.157+00:00",
                    },
                  ],
                  creationDate: "2025-05-16T08:10:13.610+00:00",
                },
                creationDate: "2025-05-16T08:10:13.606+00:00",
              },
              {
                id: 51,
                description: "action description 51",
                note: "update note 51",
                status: "Completed",
                actionType: "Automated",
                asset: {
                  id: 10,
                  shipId: 2,
                  externalAssetId: 3,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "2",
                  frame: "202",
                  type: "SW",
                  mvz: "5",
                  position: "PS",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "HVAC",
                      id: 17,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-16T08:10:14.146+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 18,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-16T08:10:14.157+00:00",
                    },
                  ],
                  creationDate: "2025-05-16T08:10:13.610+00:00",
                },
                creationDate: "2025-05-16T08:10:13.606+00:00",
              },
            ],
            creationDate: "2025-05-16T08:10:13.597+00:00",
          },
          creationDate: "2025-05-16T08:10:13.589+00:00",
        },
        {
          id: 14,
          name: "event_name_187",
          description: "event description 187",
          type: "type",
          eventDate: "2025-05-17T07:18:24.845+00:00",
          alertLog: "alertLog_187",
          status: "New",
          remediation: {
            id: 9,
            remediationCatalogId: 1,
            description: "remediation description 187",
            status: "New",
            actions: [
              {
                id: 11,
                description: "action description 187",
                note: "update note 187",
                status: "New",
                actionType: "Human",
                asset: {
                  id: 11,
                  shipId: 2,
                  externalAssetId: 3,
                  pieceMark: "A1",
                  description: "create description",
                  assetRole: "source",
                  deck: "1",
                  frame: "88",
                  type: "SW",
                  mvz: "3",
                  position: "SB",
                  ipAddress: "2.2.2.2",
                  macAddress: "BC:BC:BC:BC:BC:BC",
                  shipFunctions: [
                    {
                      function: "Navigation",
                      id: 19,
                      pieceMark: "A1",
                      percentage: "100",
                      creationDate: "2025-05-17T08:10:14.146+00:00",
                    },
                    {
                      function: "functionName2",
                      id: 20,
                      pieceMark: "A1",
                      percentage: "50",
                      creationDate: "2025-05-17T08:10:14.157+00:00",
                    },
                  ],
                  creationDate: "2025-05-17T08:10:13.610+00:00",
                },
                creationDate: "2025-05-17T08:10:13.606+00:00",
              },
            ],
            creationDate: "2025-05-17T08:10:13.597+00:00",
          },
          creationDate: "2025-05-17T08:10:09.944+00:00",
        },
      ],
      creationDate: "2025-05-15T08:10:09.941+00:00",
    },
  ];

  getIncidentDetail(incidentId: string | number): Observable<IncidentDetail[]> {
    if (environment.isMockActive) {
      return of(this.mockedIncidentDetail);
    } else {
      const apiurl = API_ENDPOINTS["retrieve_single_incident"];
      return this.apiService
        .get<IncidentDetailResponse>(`${apiurl}/${incidentId}`)
        .pipe(
          map((incidentDetailResponse) => incidentDetailResponse?.incidents)
        );
    }
  }
}
